# Generated by Django 4.2.4 on 2024-11-02 04:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativaOpcaoQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição da opção do quiz')),
                ('correta', models.BooleanField(default=True, help_text='Indica se a alternativa está correta', verbose_name='Correta?')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a alternativa está ativo', verbose_name='Está ativo?')),
            ],
            options={
                'verbose_name': 'Alternativa opção do quiz',
                'verbose_name_plural': 'Alternativas das opções do quiz',
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Desafio')),
                ('descricao', models.TextField(verbose_name='Descrição do Desafio')),
                ('dificuldade', models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado')], default=1, verbose_name='Nível do Desafio')),
                ('estimativa', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Estimativa de tempo em minutos')),
                ('ordem', models.IntegerField(default=5, verbose_name='Ordenação')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o desafio está ativo', verbose_name='Está ativo?')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Linguagem',
                'verbose_name_plural': 'Linguagem',
                'ordering': ['id', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=200, verbose_name='Descrição da opção do quiz')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a opcao está ativo', verbose_name='Está ativo?')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordenação')),
                ('alternativas', models.ManyToManyField(to='desafios.alternativaopcaoquiz', verbose_name='Opções do Quiz')),
            ],
            options={
                'verbose_name': 'Opção do quiz',
                'verbose_name_plural': 'Opções do quiz',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=300, verbose_name='Titulo do quiz')),
                ('descricao', models.TextField(max_length=20000, verbose_name='Descrição do quiz')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o quiz está ativo', verbose_name='Está ativo?')),
                ('opcoes', models.ManyToManyField(to='desafios.opcaoquiz', verbose_name='Opções do Quiz')),
                ('quemCadastrou', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa', verbose_name='Quem cadastrou')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='TipoTutorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Tipo de Tutorial',
                'verbose_name_plural': 'Tipos de Tutoriais',
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=300, verbose_name='Titulo da trilha')),
                ('descricao', models.TextField(max_length=2000, verbose_name='Descrição da Trilha')),
                ('desafios', models.ManyToManyField(to='desafios.desafio', verbose_name='Desafios da trilha')),
                ('linguagem', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='desafios.linguagem', verbose_name='Linguagem da trilha')),
            ],
            options={
                'verbose_name': 'Trilha de Conteúdo',
                'verbose_name_plural': 'Trilhas de Conteúdos',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('assunto', models.TextField(max_length=50000, verbose_name='Assunto/Descrição')),
                ('nivel', models.IntegerField(choices=[(0, 'Básico'), (1, 'Intermediário'), (2, 'Avançado')], verbose_name='Nível')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quemCadastrou', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa', verbose_name='Quem Cadastrou')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoriais', to='desafios.tipotutorial', verbose_name='Tipo')),
                ('topico', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.topico', verbose_name='Tópico no Fórum')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.trilha', verbose_name='Trilha')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriais',
            },
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('resultado', models.IntegerField(choices=[(1, 'Correta'), (2, 'Incorreta')], default=1, verbose_name='Resultado')),
                ('dataSubmissao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Submissão')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa', verbose_name='Pessoa')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissao', to='desafios.desafio')),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
                'ordering': ['problema__id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Solucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.CharField(max_length=200, verbose_name='Entrada')),
                ('secreta', models.BooleanField(default=True, help_text='Indica se o solucao é secreta', verbose_name='Secreta?')),
                ('saida', models.CharField(max_length=200, verbose_name='Saida')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o solucao está ativo', verbose_name='Está ativo?')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desafios.desafio', verbose_name='Desafio')),
            ],
            options={
                'verbose_name': 'Solução do desafio',
                'verbose_name_plural': 'Soluções dos desafios',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('alternativaSelecionada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desafios.alternativaopcaoquiz', verbose_name='Alternativa da opcao do Quiz')),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desafios.opcaoquiz', verbose_name='Opção do Quiz')),
                ('quemRespondeu', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa', verbose_name='Quem Respondeu')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desafios.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Resposta da opção do quiz',
                'verbose_name_plural': 'Respostas da opções do quiz',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='trilha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='desafios.trilha', verbose_name='Trilha do quiz'),
        ),
        migrations.CreateModel(
            name='Emblema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Emblema')),
                ('descricao', models.TextField(verbose_name='Descrição do Emblema')),
                ('imagem', models.ImageField(upload_to='emblemas/', verbose_name='Imagem do Emblema')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.trilha')),
            ],
            options={
                'verbose_name': 'Emblema',
                'verbose_name_plural': 'Emblemas',
                'ordering': ['id', 'trilha', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Documentação')),
                ('descricao', models.TextField(blank=True, max_length=50000, null=True, verbose_name='Descrição da Documentação')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quemCadastrou', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa', verbose_name='Quem Cadastrou')),
                ('tipo', models.ForeignKey(help_text='Guias, Manuais', on_delete=django.db.models.deletion.PROTECT, to='desafios.linguagem', verbose_name='Tipo da Documentação')),
            ],
            options={
                'verbose_name': 'Documentação',
                'verbose_name_plural': 'Documentações',
                'ordering': ['dataCadastro', 'nome'],
            },
        ),
    ]
