# Generated by Django 4.2.4 on 2023-09-05 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0004_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Desafio')),
                ('descricao', models.TextField(verbose_name='Descrição do Desafio')),
                ('solucao', models.CharField(help_text='Solução do desafio ou saída esperada', max_length=200, verbose_name='Solução do Desafio')),
                ('dificuldade', models.CharField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado')], verbose_name='Nível do Desafio')),
            ],
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('resultado', models.CharField(max_length=300)),
                ('dataSubmissao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Submissão')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa', verbose_name='Pessoa')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissao', to='desafios.desafio')),
            ],
        ),
    ]
