# Generated by Django 4.2.4 on 2023-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desafios", "0005_alter_submissao_pessoa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trilha",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.TextField(max_length=300, verbose_name="Titulo da trilha"),
                ),
                ("descricao", models.TextField()),
                (
                    "desafios",
                    models.ManyToManyField(
                        to="desafios.desafio", verbose_name="Desafios da trilha"
                    ),
                ),
            ],
        ),
    ]
