# Generated by Django 4.2.4 on 2023-10-08 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_perfil'),
        ('desafios', '0009_alter_desafio_options_alter_trilha_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo da opção do quiz')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição da opção do quiz')),
                ('correta', models.BooleanField(default=True, help_text='Indica se a opcao está correta', verbose_name='Correta?')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a opcao está ativo', verbose_name='Está ativo?')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordenação')),
            ],
            options={
                'verbose_name': 'Opção do quiz',
                'verbose_name_plural': 'Opções do quiz',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=300, verbose_name='Titulo do quiz')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição do quiz')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o quiz está ativo', verbose_name='Está ativo?')),
                ('opcoes', models.ManyToManyField(to='desafios.opcaoquiz', verbose_name='Opções do Quiz')),
                ('quemCadastrou', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa', verbose_name='Quem cadastrou')),
                ('trilha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='desafios.trilha', verbose_name='Trilha do quiz')),
            ],
            options={
                'verbose_name': 'Solução do desafio',
                'verbose_name_plural': 'Soluções dos desafios',
            },
        ),
    ]
