# Generated by Django 4.2.4 on 2023-11-06 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_perfil_datacadastro'),
        ('desafios', '0011_alternativaopcaoquiz_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTutorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Tipo de Tutorial',
                'verbose_name_plural': 'Tipos de Tutoriais',
            },
        ),
        migrations.AlterModelOptions(
            name='linguagem',
            options={'ordering': ['id', 'nome'], 'verbose_name': 'Linguagem', 'verbose_name_plural': 'Linguagem'},
        ),
        migrations.AlterModelOptions(
            name='submissao',
            options={'ordering': ['problema__id', 'id'], 'verbose_name': 'Submissão', 'verbose_name_plural': 'Submissões'},
        ),
        migrations.AlterModelOptions(
            name='trilha',
            options={'verbose_name': 'Trilha de Conteúdo', 'verbose_name_plural': 'Trilhas de Conteúdos'},
        ),
        migrations.RemoveField(
            model_name='alternativaopcaoquiz',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='documentacao',
            name='arquivo',
        ),
        migrations.AlterField(
            model_name='documentacao',
            name='descricao',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='Descrição da Documentação'),
        ),
        migrations.AlterField(
            model_name='documentacao',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Documentação'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='descricao',
            field=models.TextField(max_length=20000, verbose_name='Descrição do quiz'),
        ),
        migrations.AlterField(
            model_name='solucao',
            name='entrada',
            field=models.CharField(max_length=200, verbose_name='Solucao'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='descricao',
            field=models.TextField(max_length=2000, verbose_name='Descrição da Trilha'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='linguagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='desafios.linguagem', verbose_name='Linguagem da trilha'),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('assunto', models.TextField(max_length=50000, verbose_name='Assunto/Descrição')),
                ('nivel', models.CharField(choices=[(0, 'Básico'), (1, 'Intermediário'), (2, 'Avançado')], verbose_name='Nível')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quemCadastrou', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa', verbose_name='Quem Cadastrou')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.tipotutorial', verbose_name='Tipo')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.trilha', verbose_name='Trilha')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutoriais',
            },
        ),
        migrations.CreateModel(
            name='Emblema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Emblema')),
                ('descricao', models.TextField(verbose_name='Descrição do Emblema')),
                ('imagem', models.ImageField(upload_to='emblemas/', verbose_name='Imagem do Emblema')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.trilha')),
            ],
        ),
    ]
