# Generated by Django 4.2.4 on 2023-11-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("desafios", "0013_alter_emblema_options_tutorial_topico"),
    ]

    operations = [
        migrations.AddField(
            model_name="solucao",
            name="saida",
            field=models.CharField(default=0, max_length=200, verbose_name="Saida"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="solucao",
            name="entrada",
            field=models.CharField(max_length=200, verbose_name="Entrada"),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="nivel",
            field=models.CharField(
                choices=[("0", "Básico"), ("1", "Intermediário"), ("2", "Avançado")],
                verbose_name="Nível",
            ),
        ),
        migrations.AlterField(
            model_name="tutorial",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutoriais",
                to="desafios.tipotutorial",
                verbose_name="Tipo",
            ),
        ),
    ]
