# Generated by Django 4.2.4 on 2023-10-17 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_topico_subsecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dataCadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='respostapost',
            name='dataCadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='topico',
            name='dataCadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='subsecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.subsecao', verbose_name='subsecao'),
        ),
    ]
