# Generated by Django 4.2.4 on 2024-11-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome de Perfil')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem que será mostrada em seu Perfil', null=True, upload_to='imagem/perfil', verbose_name='Imagem de Perfil')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['nome', 'ativo'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.CharField(max_length=255, null=True, unique=True, verbose_name='Email principal')),
                ('contato', models.CharField(blank=True, default=None, help_text='Fone de contato com DDD (63) 98765-4321', max_length=255, null=True, verbose_name='Fone de contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('sexo', models.CharField(blank=True, choices=[(None, 'Ainda não verificado'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=2, null=True, verbose_name='Sexo')),
                ('dataNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro')),
                ('dataUltimaAlteracao', models.DateTimeField(auto_now=True, null=True, verbose_name='Última alteração')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nomeCompleto', 'ativo'],
            },
        ),
    ]
