# Generated by Django 4.2.4 on 2023-10-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dataCadastro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Cadastro'),
        ),
    ]
