# Generated by Django 4.2.4 on 2023-09-05 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_pessoa_ativo_alter_pessoa_nomecompleto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome de Perfil')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem que será mostrada em seu Perfil', null=True, upload_to='imagem/perfil', verbose_name='Imagem de Perfil')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['nome', 'ativo'],
            },
        ),
    ]
