# Generated by Django 4.2.4 on 2023-11-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0012_tipotutorial_alter_linguagem_options_and_more'),
        ('cadastro', '0005_perfil_datacadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='emblemasGanhos',
            field=models.ManyToManyField(related_name='emblemasDoUsuario', to='desafios.emblema'),
        ),
    ]
