# Generated by Django 4.2.4 on 2023-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0002_desafio_estimativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado')], default=1, verbose_name='Nível do Desafio'),
        ),
    ]
