# Generated by Django 4.2.4 on 2023-09-18 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_perfil'),
        ('desafios', '0003_alter_desafio_dificuldade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa', unique=True, verbose_name='Pessoa'),
        ),
    ]
