# Generated by Django 4.2.4 on 2023-10-02 16:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_perfil'),
        ('desafios', '0006_trilha'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinguagemDocumentacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Linguagem da Documentação',
                'verbose_name_plural': 'Linguagem da Documentação',
                'ordering': ['id', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Documentação:')),
                ('descricao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição da Documentação')),
                ('arquivo', models.FileField(upload_to='biblioteca/repositorio/', verbose_name='Arquivo')),
                ('dataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('dataAlteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('quemCadastrou', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.pessoa', verbose_name='Quem Cadastrou')),
                ('tipo', models.ForeignKey(help_text='Guias, Manuais', on_delete=django.db.models.deletion.PROTECT, to='desafios.linguagemdocumentacao', verbose_name='Tipo da Documentação')),
            ],
            options={
                'verbose_name': 'Documentação',
                'verbose_name_plural': 'Documentações',
                'ordering': ['dataCadastro', 'nome'],
            },
        ),
    ]
