# Generated by Django 4.2.4 on 2023-10-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0007_linguagemdocumentacao_documentacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinguagemDocumentacao',
            new_name='Linguagem',
        ),
    ]
