# Generated by Django 4.2.4 on 2023-10-08 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0008_rename_linguagemdocumentacao_linguagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desafio',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterModelOptions(
            name='trilha',
            options={'verbose_name': 'Solução do desafio', 'verbose_name_plural': 'Soluções dos desafios'},
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='solucao',
        ),
        migrations.AddField(
            model_name='desafio',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o desafio está ativo', verbose_name='Está ativo?'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='ordem',
            field=models.IntegerField(default=5, verbose_name='Ordenação'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='linguagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='desafios.linguagem', verbose_name='Linguagem da trilha'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='resultado',
            field=models.IntegerField(choices=[(1, 'Correta'), (2, 'Incorreta')], default=1, verbose_name='Tipo de Local'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Descrição da Trilha'),
        ),
        migrations.CreateModel(
            name='Solucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.CharField(max_length=200, verbose_name='Título do solucao')),
                ('secreta', models.BooleanField(default=True, help_text='Indica se o solucao é secreta', verbose_name='Secreta?')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o solucao está ativo', verbose_name='Está ativo?')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='desafios.desafio', verbose_name='Desafio')),
            ],
            options={
                'verbose_name': 'Solução do desafio',
                'verbose_name_plural': 'Soluções dos desafios',
            },
        ),
    ]
